<div class="body">
	<div class="breadcrumb">
		<a href="<?= Tool::getUrl() ?>">首页</a>
		<span>></span>
		<a href="<?= Tool::getUrl('list/all/index')?>">全部</a>
	</div>
	<div class="w">
		<ul class="list">
			<?php
			foreach($list as $v) {
				echo '<li><a href="',Tool::getUrl('list/detail/index'),'">',$v['title'],'</a></li>';
			}
			?>
		</ul>
		<ul class="pager">
			<li><a href="##"><<</a></li>
			<li><a href="##"><</a></li>
			<li><a href="##">...</a></li>
			<li><a href="##">6</a></li>
			<li><a href="##">7</a></li>
			<li><a href="##">8</a></li>
			<li><a href="##">9</a></li>
			<li><a href="##">10</a></li>
			<li><a href="##">...</a></li>
			<li><a href="##">></a></li>
			<li><a href="##">>></a></li>
			<li><input type="text"></li>
			<li><input type="button" value="Go"></li>
		</ul>
	</div>
</div>